---

blank_issues_enabled: false
contact_links:
  - name: Discord support
    url: https://unmanic.app/discord
    about: Ask questions in Discord.
  - name: Community guides
    url: https://docs.unmanic.app/docs/
    about: For all guides 
  - name: Unraid Forum
    url: https://forums.unraid.net/topic/76878-support-josh5-unmanic-library-optimiser/
    about: For Unraid users, please check the forums to see if your question has already been answered.
