---

name: New Plugin Request
description: Suggest a new plugin.
labels: ['status:awaiting-triage', 'type:plugin-request']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help improve!

        Please be sure to first explore the current options available before making this request.

        Also please be a proactive community member. Have you tried to create the plugin yourself? We welcome PRs for new plugins.

        If you are unable to create the plugin, consider supporting development and I will see about making it for you.
  - type: textarea
    id: plugin
    attributes:
      label: What is your new plugin request?
      description: A clear and concise description of the new plugin.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots / mockups about the new plugin request here.
